worker_processes auto;

events {
    worker_connections 256;
}

http {
    include /etc/nginx/mime.types;

    server {
        listen 80;

        # — Landing page
        location = / {
            add_header Cache-Control "no-cache";
            alias /usr/share/nginx/html/;
            try_files /index.html =404;
        }

        # — Glance
        location /glance/ {
            proxy_pass http://glance:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # — Quartz
        location /quartz/ {
            proxy_pass http://quartz:8082/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # — Glances
        location /glances/ {
            proxy_pass http://glances:61208/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
